README.md
=> Klaviyo related changes

.github/workflows/create_release_notes.yaml, .github/workflows/release.yaml, .github/workflows/server_docker_hub_push.yaml, .github/workflows/ui_docker_hub_push.yaml
feat: Release process automation
https://github.com/Multiwoven/multiwoven/issues/14
Tested by forking the repo and trying the workflow
=> feat: Release process automation

server/lib/reverse_etl/extractors/incremental_delta.rb, server/spec/lib/reverse_etl/extractors/incremental_delta_spec.rb
=> fix: add primary key validation for extractor

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/protocol/protocol.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/lib/multiwoven/integrations/source/bigquery/config/spec.json, integrations/lib/multiwoven/integrations/source/databricks/config/spec.json, integrations/lib/multiwoven/integrations/source/postgresql/config/spec.json, integrations/lib/multiwoven/integrations/source/redshift/config/spec.json, integrations/lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/config/spec.json, integrations/lib/multiwoven/integrations/source/snowflake/config/spec.json, integrations/spec/multiwoven/integrations/protocol/protocol_spec.rb
=> fix: add connector_query_type in spec

release-notes.md
This PR updates the release-notes.md for the upcoming release. Please review and merge to trigger the release.
=> Multiwoven release v0.2.0

.env.example, docker-compose.yml
- Updated env file configuration to match prod setup
- Updated docker-compose file to pick Dockerfile prod
- Tested to build locally
=> Updated dockerfile and env to run docker-compose on prod mode.

.github/workflows/create-release-notes.yaml
Update create release to use github token
None
Not Tested
=> Update create release to use github token

.github/workflows/integrations-ci.yml, .github/workflows/server-ci.yml, .github/workflows/server-docker-build.yml, .github/workflows/ui-ci.yml, .github/workflows/ui-docker-build.yml
feat: Add code climate to GitHub actions
None
None
=> feat: Add code climate to github actions

.github/workflows/integrations-ci.yml, .github/workflows/server-ci.yml, .github/workflows/ui-ci.yml
fix: Code climate reporter path not found
None
Tested by cloning the repo and running actions
=> fix: Code climate reporter path not found

.github/workflows/integrations-gem-release.yml
feat: Automate integrations gem release
None
none
=> feat: Automate integrations gem release

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/protocol/protocol.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/protocol/protocol_spec.rb
None
add protocol changes for cursor based incremental
=> feat: add protocol changes for cursor based incremental

CONTRIBUTING.md, README.md, integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/core/base_connector.rb, integrations/lib/multiwoven/integrations/core/constants.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/multiwoven-integrations.gemspec, integrations/spec/multiwoven/integrations/destination/google_sheets/client_spec.rb, integrations/spec/multiwoven/integrations/destination/hubspot/client_spec.rb, integrations/spec/multiwoven/integrations/destination/salesforce_consumer_goods_cloud/client_spec.rb, integrations/spec/multiwoven/integrations/destination/salesforce_crm/client_spec.rb, integrations/spec/multiwoven/integrations/destination/sftp/client_spec.rb, integrations/spec/multiwoven/integrations/destination/stripe/client_spec.rb, integrations/spec/multiwoven/integrations/source/salesforce_consumer_goods/client_spec.rb
feat: Remove changes associated with individual repository
None
None
=> feat: Remove changes associated with individual repository

ui/src/components/Table/Table.tsx, ui/src/utils/types.ts, ui/src/views/Activate/Syncs/constants.ts, ui/src/views/Activate/Syncs/types.ts
- Added Hover Text for Sync Runs Table Columns
[Screencast from 04-12-2024 10:07:21 PM.webm](https://github.com/Multiwoven/multiwoven/assets/54372016/53f7aed5-b69d-497a-a5b6-46653096a520)
None
=> feat: added hover text for columns

.github/workflows/deploy-main.yml
feat: Add github action to deploy main
None
No
=> feat: Add github action to deploy main

release-notes.md
This PR updates the release-notes.md for the upcoming release. Please review and merge to trigger the release.
=> Multiwoven release v0.3.0

ui/src/components/Pagination/Pagination.tsx
Fixed the hover color for Pagination
Issue:
Fixed:
[Screencast from 04-15-2024 11:58:13 AM.webm](https://github.com/Multiwoven/multiwoven/assets/54372016/a753da74-62ed-478e-a682-69e3fdc7261a)
None
=> fix: changed color for disabled Pagination button and cursor type

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/protocol/protocol.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/client.rb, integrations/lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/schema_helper.rb, integrations/spec/multiwoven/integrations/destination/salesforce_consumer_goods_cloud/schema_helper_spec.rb, integrations/spec/multiwoven/integrations/protocol/protocol_spec.rb, integrations/spec/multiwoven/integrations/source/salesforce_consumer_goods/schema_helper_spec.rb
=> fix: add query type connector protocol

ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/ConfigureSyncs.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/MapFields.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/TemplateMapping.tsx, ui/src/views/Activate/Syncs/SyncForm/SyncForm.tsx
- The mapping layout was misaligned when the required fields were disabled
- Also fixed a small bug which was giving a blank screen upon reloading the page from step 3
- The sync mode state was not persisting, fixed this as well
https://github.com/Multiwoven/multiwoven/assets/29303618/6d0d2fb1-daa7-4310-861a-38f83718664f
=> fix: sync creation process

server/Gemfile, server/Gemfile.lock
=> chore: upgrade integrations 0.1.59

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/protocol/protocol.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/protocol/protocol_spec.rb
=> fix: add source_defined_cursor in catalog

server/Gemfile, server/Gemfile.lock
=> chore: upgrade integration to 0.1.60

server/Gemfile, server/Gemfile.lock
Update integration gem version to 0.1.61
None
None
=> Update integration gem version to 0.1.61

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/rollout.rb, integrations/lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/client.rb
=> fix: salesforce query offset removed

server/lib/reverse_etl/transformers/user_mapping.rb, server/spec/lib/reverse_etl/transformers/user_mapping_spec.rb
Reverts Multiwoven/multiwoven#59
=> Revert "fix: Remove \n from rendered liquid template data"

ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/FieldMap.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/Columns.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/StaticOptions.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/TemplateMapping.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/TemplateOptions.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/__tests__/Columns.test.tsx, ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/__tests__/TemplateOptions.test.tsx, ui/src/views/Activate/Syncs/types.ts
- During the edit, the template box was not being pre-filled with data - fixed this
- Added variable options on apply
https://github.com/Multiwoven/multiwoven/assets/29303618/c9035d11-7120-45c2-a33c-0b996df3b8ff
=> fix: update apply button condition for template mapping

ui/src/views/Activate/Syncs/EditSync/EditSync.tsx, ui/src/views/Activate/Syncs/EditSync/ScheduleForm.tsx, ui/src/views/Activate/Syncs/SyncForm/FinaliseSync/FinaliseSync.tsx, ui/src/views/Activate/Syncs/types.ts
Updated sync scheduler type for Interval mode.
=> fix: update scheduler type for manual interval

README.md
=> Updated README as per the mono-repo changes.

.github/workflows/ui-ci.yml, ui/src/views/Models/ModelsForm/FinalizeModel/FinalizeModel.tsx
- Changed Finalize Model screen to have same width and color as other screens
None
=> Refactor: models finalize screen

server/app/serializers/sync_run_serializer.rb, server/db/migrate/20240422145159_add_skip_rows_to_sync_runs.rb, server/db/migrate/20240423060924_add_skipped_rows_to_sync_runs.rb, server/db/schema.rb, server/lib/reverse_etl/extractors/incremental_delta.rb, server/spec/lib/reverse_etl/extractors/incremental_delta_spec.rb
=> fix: add skipped_rows column in sync run

ui/src/components/EntityItem/EntityItem.tsx, ui/src/views/Dashboard/Dashboard.tsx, ui/src/views/Dashboard/ListConnectors.tsx, ui/src/views/Dashboard/Reports/ChartCard.tsx, ui/src/views/Dashboard/Reports/Reports.tsx
Updated reporting dashboard layout fixes as per design reviews
- Increase spacing between tabs and boxes
- Change the font color of Headings
=> style: rerporting dashboard layout

.github/workflows/release.yaml
fix: Patch tag versioning
None
No
- [] Added relevant screenshots for the changes
=> fix: Patch tag versioning

server/Gemfile, server/Gemfile.lock, server/app/temporal/cli/worker, server/lib/utils/health_checker.rb, server/spec/lib/utils/health_checker_spec.rb
=> feat: add health check endpoint for worker

.github/workflows/ui-validate.yml, ui/package-lock.json, ui/src/views/Models/ModelsForm/DefineModel/DefineSQL/DefineSQL.tsx, ui/src/views/Models/ViewModel/ViewModel.tsx
Fixed the build which was causing build failure during auto deploy
=> fix: UI auto deploy

server/Gemfile, server/Gemfile.lock
=> chore: bump integration gem to 1.63

ui/src/chakra.config.ts
Reverted the chakra config to support brand configuration
=> chore: update config to support branding (revert)

ui/env.js, ui/index.html
Removed the env.js file and importing the envs in the index.html
=> fix: importing envs

integrations/lib/multiwoven/integrations/destination/sftp/config/spec.json, server/Gemfile, server/Gemfile.lock, server/lib/reverse_etl/utils/batch_query.rb, server/spec/lib/reverse_etl/utils/batch_query_spec.rb
=> fix: skip cursor query builder for cursor empty

ui/src/components/JSONSchemaForm/rjsf/BaseInputTemplate.tsx
[Screencast from 05-03-2024 07:45:47 PM.webm](https://github.com/Multiwoven/multiwoven/assets/54372016/3dd4d93e-9d48-41b1-9953-e806219d06f6)
=> feat: added toggle to view password field values

.gitignore, server/config/initializers/temporal.rb
=> feat: connect to temporal cloud via TLS

ui/src/components/JSONSchemaForm/JSONSchemaForm.tsx, ui/src/views/Connectors/Sources/SourcesForm/SourceConfigForm/SourceConfigForm.tsx
Removed hardcoded values in the code, specifically UI Schema and some commented code
=> Refactor: removed hardcoded ui schema

ui/src/views/Connectors/Sources/SourcesForm/SourceFinalizeForm/SourceFinalizeForm.tsx
Changed the finalize source form text from `destination` to `source`
=> fix: changed the text in the Finalize Source Form

sync_commit.sh
=> feat: sync commits from CE to EE

server/bin/docker-entrypoint, server/db/data/20240516181513_migrate_workspace_user_roles_to_admin.rb, server/db/data_schema.rb, server/db/migrate/20240515072318_add_role_id_to_workspace_users.rb, server/db/schema.rb
=> [CE] fix: role_id migration failure

server/.env.example, server/Gemfile, server/Gemfile.lock, server/app/controllers/concerns/exception_handler.rb, server/app/interactors/authentication/login.rb, server/app/interactors/authentication/logout.rb, server/app/interactors/connectors/query_source.rb, server/app/models/sync.rb, server/app/temporal/activities/schedule_sync_activity.rb, server/app/temporal/middlewares/logging_middleware.rb, server/lib/reverse_etl/extractors/full_refresh.rb, server/lib/reverse_etl/extractors/incremental_delta.rb, server/lib/reverse_etl/loaders/standard.rb, server/lib/reverse_etl/transformers/user_mapping.rb, server/lib/utils/exception_reporter.rb, server/spec/lib/utils/exception_reporter_spec.rb
=> [CE] feat: appsignal integration

server/db/migrate/20240515072318_add_role_id_to_workspace_users.rb
=> [CE] fix: role id null in migration

server/Gemfile, server/Gemfile.lock, server/app/controllers/api/v1/syncs_controller.rb, server/app/controllers/application_controller.rb, server/app/controllers/concerns/exception_handler.rb, server/app/models/workspace_user.rb, server/app/policies/application_policy.rb, server/app/policies/sync_policy.rb, server/spec/requests/api/v1/syncs_controller_spec.rb
=> [CE] feat: integrate pundit for authorization

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/config.rb, integrations/lib/multiwoven/integrations/core/utils.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/lib/multiwoven/integrations/service.rb, integrations/spec/multiwoven/integrations/config_spec.rb, integrations/spec/multiwoven/integrations/core/utils_spec.rb, integrations/spec/multiwoven/integrations/service_spec.rb
=> [CE] feat: report errors to appsignal from integrations

server/Gemfile.lock, server/config/initializers/logging.rb, server/config/initializers/temporal.rb
=> [CE] feat: add appsignal logging

server/Gemfile.lock, server/config/initializers/logging.rb, server/config/initializers/temporal.rb
Reverts Multiwoven/multiwoven#147
=> Revert "[CE] feat: add appsignal logging"

server/Gemfile.lock, server/config/initializers/logging.rb, server/config/initializers/temporal.rb
=> [CE] feat: send logs to appsignal

ui/src/views/Authentication/SignIn/SignIn.tsx
Removed `Forgot Password` text from the Sign In screen
=> Removed forgot password text

ui/src/views/Connectors/Destinations/DestinationsForm/SelectDestinations/SelectDestinations.tsx
Fixed badge alignment and rows of connectors to take up full width
=> Fixed styling for select destination screen

ui/src/components/JSONSchemaForm/JSONSchemaForm.tsx, ui/src/components/JSONSchemaForm/rjsf/WrapIfAdditionalTemplate.tsx
=> style: fixed key value pair rendering

git-hooks/commit-msg, server/app/interactors/authentication/logout.rb, server/app/models/sync.rb, server/app/temporal/activities/schedule_sync_activity.rb, server/db/seeds.rb, server/lib/reverse_etl/extractors/full_refresh.rb, server/lib/reverse_etl/extractors/incremental_delta.rb, server/lib/reverse_etl/loaders/standard.rb, server/lib/reverse_etl/transformers/user_mapping.rb, server/lib/utils/exception_reporter.rb, server/spec/lib/utils/exception_reporter_spec.rb
=> [CE] feat: add meta data support while sending exception

server/Gemfile, server/Gemfile.lock, server/app/mailers/devise_mailer.rb, server/app/models/user.rb, server/app/serializers/user_serializer.rb, server/app/views/devise/mailer/invitation_instructions.html.erb, server/config/initializers/devise.rb, server/config/locales/devise_invitable.en.yml, server/db/migrate/20240521134208_add_invitation_fields_to_users.rb, server/db/migrate/20240522101110_devise_invitable_add_to_users.rb, server/db/migrate/20240523093913_add_unique_index_to_workspace_users.rb, server/db/schema.rb, server/spec/interactors/authentication/signup_spec.rb, server/spec/models/user_spec.rb
=> [CE] feat: add devise_invitable gem for user invite

server/app/controllers/api/v1/connectors_controller.rb, server/app/controllers/api/v1/models_controller.rb, server/lib/utils/query_validator.rb, server/spec/lib/utils/query_validator_spec.rb, server/spec/requests/api/v1/connectors_controller_spec.rb, server/spec/requests/api/v1/models_controller_spec.rb
fix: comment query validation as it's failing for BigQuery
None
=> fix: comment query validation as it's failing for BigQuery

server/app/views/devise/mailer/invitation_instructions.html.erb, server/spec/factories/users.rb
=> [CE] chore: add invited user params in user factory

integrations/Gemfile, integrations/Gemfile.lock, integrations/lib/multiwoven/integrations.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/lib/multiwoven/integrations/source/clickhouse/client.rb, integrations/lib/multiwoven/integrations/source/clickhouse/config/meta.json, integrations/lib/multiwoven/integrations/source/clickhouse/config/spec.json, integrations/lib/multiwoven/integrations/source/clickhouse/icon.svg, integrations/spec/multiwoven/integrations/source/clickhouse/client_spec.rb
Adding Clickhouse Connector
https://linear.app/ai-squared/issue/BE-78/clickhouse-source-connector
Rspec
=> feat: Add Clickhouse connector

server/app/models/sync.rb, server/spec/models/sync_spec.rb
=> [CE] fix: invalid aasm transition

ui/src/chakra-core.config.ts
Changed the styling of the select dropdown
=> Fixed select dropdown styling

server/app/models/resource.rb, server/spec/models/resource_spec.rb
=> [CE] fix: Add resource model as common

server/db/data/20240524141637_update_workspace_users_to_admin_role.rb, server/db/data_schema.rb
=> [CE] fix: workspace user role fix migration

server/app/contracts/workspace_contracts.rb, server/spec/requests/api/v1/workspaces_controller_spec.rb
=> [CE] fix: workspace creation optional variable accept empty

server/app/mailers/devise_mailer.rb, server/app/views/devise/mailer/invitation_instructions.html.erb
=> [CE] fix: missing invited user email in template

server/Gemfile, server/Gemfile.lock, server/lib/reverse_etl/extractors/incremental_delta.rb, server/spec/lib/reverse_etl/extractors/incremental_delta_spec.rb
=> [CE] feat: destination update with status pending

server/app/controllers/api/v1/users_controller.rb, server/spec/requests/api/v1/users_controller_spec.rb
=> fix(CE): add role in user info api  response

server/app/temporal/activities/loader_activity.rb, server/lib/reverse_etl/loaders/standard.rb
=> chore(CE): update the heartbeat timeout for loader (#188)

server/Gemfile, server/Gemfile.lock, server/lib/reverse_etl/loaders/standard.rb, server/spec/lib/reverse_etl/loaders/standard_spec.rb
=> [CE] fix: sync write update action for destination

server/app/controllers/api/v1/auth_controller.rb, server/app/controllers/api/v1/connector_definitions_controller.rb, server/app/controllers/api/v1/connectors_controller.rb, server/app/controllers/api/v1/models_controller.rb, server/app/controllers/api/v1/reports_controller.rb, server/app/controllers/api/v1/sync_records_controller.rb, server/app/controllers/api/v1/sync_runs_controller.rb, server/app/controllers/api/v1/syncs_controller.rb, server/app/controllers/api/v1/users_controller.rb, server/app/controllers/api/v1/workspaces_controller.rb, server/app/controllers/application_controller.rb, server/app/policies/application_policy.rb, server/app/policies/connector_definition_policy.rb, server/app/policies/connector_policy.rb, server/app/policies/current_context.rb, server/app/policies/model_policy.rb, server/app/policies/report_policy.rb, server/app/policies/sync_record_policy.rb, server/app/policies/sync_run_policy.rb, server/app/policies/user_policy.rb, server/app/policies/workspace_policy.rb, server/spec/requests/api/v1/connector_definitions_spec.rb, server/spec/requests/api/v1/connectors_controller_spec.rb, server/spec/requests/api/v1/models_controller_spec.rb, server/spec/requests/api/v1/reports_controller_spec.rb, server/spec/requests/api/v1/sync_records_controller_spec.rb, server/spec/requests/api/v1/sync_runs_controller_spec.rb, server/spec/requests/api/v1/syncs_controller_spec.rb, server/spec/requests/api/v1/users_controller_spec.rb, server/spec/requests/api/v1/workspaces_controller_spec.rb
=> (CE)feat: added RBAC for all apis

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/core/destination_connector.rb, integrations/lib/multiwoven/integrations/core/fullrefresher.rb, integrations/lib/multiwoven/integrations/core/query_builder.rb, integrations/lib/multiwoven/integrations/core/rate_limiter.rb, integrations/lib/multiwoven/integrations/destination/facebook_custom_audience/client.rb, integrations/lib/multiwoven/integrations/destination/klaviyo/client.rb, integrations/lib/multiwoven/integrations/destination/postgresql/client.rb, integrations/lib/multiwoven/integrations/destination/sftp/client.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/core/fullrefresher_spec.rb, integrations/spec/multiwoven/integrations/core/query_builder_spec.rb, integrations/spec/multiwoven/integrations/core/rate_limiter_spec.rb, integrations/spec/multiwoven/integrations/destination/sftp/client_spec.rb
fix(CE): Update insert and update to destination_insert and destination_update action
None
None
=> fix(CE): Update insert and update to destination_insert and destination_update action

server/Gemfile, server/Gemfile.lock, server/config/initializers/strong_migrations.rb
chore(CE): Add strong migration gem
None
Tested locally
=> chore(CE): Add strong migration gem

server/app/contracts/sync_contracts.rb
fix(CE): Comment contract valid rule in Update Sync action
None
=> fix(CE): Comment contract valid rule in Update Sync action

server/app/contracts/model_contracts.rb, server/spec/contracts/model_contracts_spec.rb
fix(CE): Add limit and offset query validator 
None
=> fix(CE): Add limit and offset query validator

server/app/controllers/api/v1/workspaces_controller.rb, server/app/policies/workspace_policy.rb, server/spec/requests/api/v1/workspaces_controller_spec.rb
=> fix(CE): ignore rbac for get workspaces api (#207)

.github/workflows/sync-ce-commits.yaml
fix(CE): EE to CE Commit Sync PAT issue
None
Will test after deployment
=> fix(CE): EE to CE Commit Sync PAT issue

.github/workflows/sync-ce-commits.yaml
fix(CE): Github URL issues
None
Have not testes
=> fix(CE): Github URL issues

.github/workflows/sync-ce-commits.yaml
fix: CE sync commit not working for multiple commits
None
Yes, test in karthik/multiwoven repo
=> fix: CE sync commit not working for multiple commits

.github/workflows/integrations-ci.yml, .github/workflows/server-ci.yml, .github/workflows/ui-ci.yml, README.md
Updating workflows so each project reports separately to Code Climate, producing separate badges.
=> feat(CE): separate code climate reports and badges

server/db/migrate/20240614135415_remove_error_from_sync_records.rb, server/db/migrate/20240614140619_add_error_json_to_sync_records.rb, server/db/schema.rb, server/spec/requests/api/v1/sync_records_controller_spec.rb
=> fix(CE): json error field added in sync record

server/db/data/20240617095053_update_role_policies.rb, server/db/data_schema.rb
=> chore(CE): update the role policies

ui/src/stores/useSyncStore.ts, ui/src/views/Activate/Syncs/SyncRecords/ErrorLogsModal.tsx, ui/src/views/Activate/Syncs/SyncRecords/FilterTabs.tsx, ui/src/views/Activate/Syncs/SyncRecords/SyncRecords.tsx, ui/src/views/Activate/Syncs/SyncRecords/SyncRecordsTableItem.tsx, ui/src/views/Activate/Syncs/SyncRecords/SyncRecordsTopBar.tsx, ui/src/views/Activate/Syncs/ViewSync/ViewSync.tsx, ui/src/views/Activate/Syncs/__tests__/SyncRecordTableItem.test.tsx, ui/src/views/Activate/Syncs/types.ts
=> feat(CE): Sync records error log

server/Gemfile, server/Gemfile.lock
=> chore(CE): update server gem

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/destination/maria_db/client.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/destination/maria_db/client_spec.rb
Add request response log to MariaDB
https://linear.app/ai-squared/issue/BE-272/request-response-log-for-mariadb-destination-connector-write
=> chore(CE): add request response log for MariaDB

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/destination/google_sheets/client.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/destination/google_sheets/client_spec.rb
Add request response log to Google Sheets
https://linear.app/ai-squared/issue/BE-269/request-response-log-for-googlesheets-destination-connector-write
=> chore(CE): add request response log for Google Sheets

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/destination/iterable/client.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/destination/iterable/client_spec.rb
Add request response log to Iterable
https://linear.app/ai-squared/issue/BE-270/request-response-log-for-iterable-destination-connector-write
=> chore(CE): add request response log for Iterable

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/destination/zendesk/client.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/destination/zendesk/client_spec.rb
Add request response log to Zendesk
https://linear.app/ai-squared/issue/BE-274/request-response-log-for-module-zendesk-destination-connector-write
=> chore(CE): add request response log for Zendesk

server/lib/reverse_etl/extractors/base.rb
This PR cherry-picks the CE commit 0fa7c8e4ee6b083d5a4ff3eed2e4d64ad2028c99 from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> fix(CE): memory bloat issue in sync

server/app/controllers/api/v1/connectors_controller.rb, server/spec/requests/api/v1/connectors_controller_spec.rb
This PR cherry-picks the CE commit da444b861228226b8035d06dd50011f53f6b4ff4 from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> chore(CE): update the query_source response

server/db/data/20240813084446_update_user_read_permission.rb, server/db/data_schema.rb
This PR cherry-picks the CE commit 0e6165f880176d75120aac9019516b7c22d0975d from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> chore(CE): update user read permission (#382)

.github/workflows/deploy-server.yml, .github/workflows/deploy-ui.yml
Adds workflows to auto-deploy UI, server and worker, on changes to main.
=> feat(CE): added workflows for auto-deployment

.github/workflows/deploy-server.yml, .github/workflows/deploy-ui.yml
Adding more keys to `runs-on` so it selects the runner we built outside GitHub.
Can't test until merged and a workflow is triggered.
=> fix: adding more labels to self-hosted runner

server/app/controllers/api/v1/connectors_controller.rb, server/app/interactors/connectors/create_connector.rb, server/spec/interactors/connectors/create_connector_spec.rb
This PR cherry-picks the CE commit 351b22896711bdafd485acb56abe9bd15c8c6fa6 from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): prevent duplicate names for source connectors

server/db/migrate/20240923143812_add_data_app_token_to_data_apps.rb, server/db/migrate/20240923150740_populate_data_app_token_and_add_index.rb, server/db/schema.rb
This PR cherry-picks the CE commit cf7f9380fd98ac750568a57aed39ecf29aa567f4 from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> chore(CE): add data_app_token with unique constraint

server/app/models/connector.rb, server/app/models/data_app.rb, server/app/models/visual_component.rb, server/spec/factories/data_apps.rb, server/spec/factories/roles.rb, server/spec/factories/visual_components.rb, server/spec/models/data_app_spec.rb, server/spec/models/visual_component_spec.rb
This PR cherry-picks the CE commit 9d12dafe0eac21363040ab68561cbc07606466b2 from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> chore(CE): Add data_app_token generation

ui/src/views/Sidebar/Sidebar.tsx
- Fixed the Dashboard SideBar Responsiveness issue
https://github.com/user-attachments/assets/fd824a0b-efc6-4956-a54c-5b22de80a96d
Relates to issue #101 - 'Fixed Dashboard SideBar Responsiveness issue'
1. Login to the Dashboard.
2. Check the UI of Dashboard in different screen sizes to see the issue fix.
=> fix(CE): dashboard sidebar responsiveness

server/lib/script_vault/tracker.rb
=> fix(CE): add exception to tracker

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations/rollout.rb, integrations/multiwoven-integrations.gemspec
=> fix(CE): mailchimp dependency build issue

server/Dockerfile
=> fix(CE): Dockerfile update free tds

.github/workflows/deploy-server.yml, .github/workflows/deploy-ui.yml
Removes reference to `build_and_push` workflow job.
[INFRA-1144](https://linear.app/ai-squared/issue/INFRA-1144/fix-ui-deployment-issue-found-during-review)
=> fix(CE): removed reference to build_and_push job

ui/src/components/ModelTable/ModelTable.tsx, ui/src/services/models.ts, ui/src/views/Models/ModelsList/ModelsList.tsx
=> feat(CE): update model query types

server/config/initializers/custom_pagination_links.rb, server/spec/requests/api/v1/models_controller_spec.rb
This PR cherry-picks the CE commit 8f4a10b2825b48bfe2255e832b7868a9e747eb71 from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> fix(CE): pagination fix for empty data

server/Gemfile, server/Gemfile.lock
This PR cherry-picks the CE commit ea77fe8cb7221b85e7e6b5ec858b06a468c9054f from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): Update Server Gem 0.18.0 (#761)

.github/workflows/deploy-server.yml
Updating workflow to deploy solid worker.
=> feat(CE): update workflow to add solid worker

.github/workflows/deploy-server.yml
Removing solid worker from workflow.
=> fix(CE): remove solid worker from workflow

.github/workflows/integrations-ci.yml, .github/workflows/integrations-main.yml, .github/workflows/server-ci.yml
=> chore(CE): Oracle Instant Client Fix

server/app/controllers/api/v1/sync_runs_controller.rb
=> fix(CE): test failure

server/app/models/role.rb, server/lib/utils/constants.rb, server/spec/factories/roles.rb, server/spec/models/role_spec.rb
=> feat(CE): add grouped resource count to role

server/config/environments/production.rb
=> fix(CE): active storage to local

server/README.md
Updated README.md for Multiwoven Server - Dependencies Installation.
This includes installation steps for Mac and Linux.
=> chore(CE): update server dependencies in readme

.github/workflows/release.yaml, .github/workflows/server-docker-hub-push-tags-amd.yaml, .github/workflows/ui-docker-hub-push-tags-amd.yml
PR for CE repo corresponding to:
https://github.com/Multiwoven/multiwoven-ee/pull/975  and 
https://github.com/Multiwoven/multiwoven-ee/pull/973
=> feat(CE): update release workflows

.github/workflows/integrations-ci.yml
=> feat(CE): update integrations-ci.yml workflow

server/app/serializers/feedback_serializer.rb, server/app/serializers/message_feedback_serializer.rb
Adds missing `tags` from feedback and message_feedback serializers.
=> fix(CE): update feedback serializer with tags

.github/workflows/sync-ce-commits.yaml
=> feat(CE): update sync-ce-commits.yaml

server/app/models/billing/plan.rb, server/app/models/billing/subscription.rb, server/spec/models/billing/plan_spec.rb, server/spec/models/billing/subscription_spec.rb
This PR cherry-picks the CE commit 0fb221deb213c110a95258ffc5148294b5949aea from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): Update API to return 'monthly' instead of 'month' (#1115)

server/app/models/organization.rb, server/app/models/workspace.rb, server/db/migrate/20250529124656_add_workspace_logos.rb, server/db/migrate/20250529125449_add_organization_logos.rb, server/db/schema.rb, server/spec/factories/organizations.rb, server/spec/factories/workspaces.rb
This PR cherry-picks the CE commit 0bf1f138a7e060ca3036fbde81733d11f8b3a0f8 from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): DB changes for logo upload

integrations/Gemfile.lock, integrations/lib/multiwoven/integrations.rb, integrations/lib/multiwoven/integrations/core/vector_source_connector.rb, integrations/lib/multiwoven/integrations/protocol/protocol.rb, integrations/lib/multiwoven/integrations/rollout.rb, integrations/spec/multiwoven/integrations/core/vector_source_connector_spec.rb, integrations/spec/multiwoven/integrations/protocol/protocol_spec.rb
This PR cherry-picks the CE commit e000ad87d531c973384c5e0a68096f0fdebbddfa from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> refactor(CE): Update Protocol for Vector_Search

server/Gemfile, server/Gemfile.lock
This PR cherry-picks the CE commit 0e2e03032c4daa9284542eec2aae6a27ff01c02a from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): Update Server Gem 0.29.0

server/config/environments/production.rb, server/config/storage.yml
This PR cherry-picks the CE commit e4f56f4919f02ea4f7cc63e3105c85b5324f309b from the Enterprise repository. Commit author: Hassim Naseef M (hassim.naseef@squared.ai)
=> chore(CE): enable s3 bucket for storage (#1175)

server/db/migrate/20250627000141_add_sub_connector_category_to_connector.rb, server/db/schema.rb
This PR cherry-picks the CE commit ca03083d1d874f6089ce965b63aa386f76a0cf60 from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): Add sub_category for connectors

server/config/application.rb
This PR cherry-picks the CE commit 94e5e5690e8d3a3af16ac0f5e942296e61f983ce from the Enterprise repository. Commit author: TivonB-AI2 (124182151+TivonB-AI2@users.noreply.github.com)
=> chore(CE): Add prevention for clickjacking

server/app/models/connector.rb, server/app/serializers/connector_serializer.rb, server/spec/models/connector_spec.rb
This PR cherry-picks the CE commit c3840ec45cfe61240238a0712102cd85346e1287 from the Enterprise repository. Commit author: afthab vp (afthab@multiwoven.com)
=> chore(CE): mask connector credentials
