README.md

Changed the links in the Documentation to redirect to the Multiwoven Docs instead of # for EC2, GCE and Helm.

Added doc links for EC2, GCE and Helm

---

ui/package-lock.json
ui/package.json
ui/src/views/Activate/Syncs/EditSync/EditSync.tsx
ui/src/views/Dashboard/Dashboard.tsx
ui/src/views/Models/ModelsForm/DefineModel/DefineSQL/DefineSQL.tsx

Added beautify for sql queries.
> Removed the extra white space in the edit sync section

feat: beautify sql queries

---

ui/src/views/Activate/Syncs/EditSync/EditSync.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/ConfigureSyncs.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/FieldMap.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/MapCustomFields.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/MapFields.tsx
ui/src/views/Connectors/Destinations/DestinationsForm/DestinationConnectionTest/DestinationConnectionTest.tsx

Removed the condition to allow any number of mapping during sync configuration.
https://github.com/Multiwoven/multiwoven/assets/29303618/9de0b697-6329-4289-a8cf-d060ec9cd3bc

fix: remove disable condition for adding more mapping

---

ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/FieldMap.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/SelectStreams.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/Columns.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/TemplateMapping.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/TemplateOptions.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/TemplateMapping/__tests__/Columns.test.tsx

Added custom dropdowns for the destination columns during syncs mapping.

feat: added custom dropdown for destination columns

---

server/app/mailers/sync_run_mailer.rb
server/app/models/sync_run.rb
server/app/views/sync_run_mailer/status_email.html.erb
server/spec/mailers/sync_run_mailer_spec.rb
server/spec/models/sync_run_spec.rb

fix: Update sync run mailer to trigger on failure only
None
Wrote rspec

fix: Update sync run mailer to trigger on failure only

---

ui/src/views/Activate/Syncs/EditSync/EditSync.tsx
ui/src/views/Connectors/Sources/SourcesForm/SourceFormFooter/SourceFormFooter.tsx

The back button was not navigating to the syncs list screen from the edit page. Fixed the issue
https://github.com/Multiwoven/multiwoven/assets/29303618/9c454694-115d-48dd-bb2f-10021f5f7e40

fix: update back button navigation on syncs configuration

---

integrations/Gemfile.lock
integrations/lib/multiwoven/integrations/protocol/protocol.rb
integrations/lib/multiwoven/integrations/rollout.rb
integrations/lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/schema_helper.rb
integrations/spec/multiwoven/integrations/source/salesforce_consumer_goods/schema_helper_spec.rb

fix: source_defined_cursor default value to false in stream

---

integrations/Gemfile.lock
integrations/lib/multiwoven/integrations/destination/salesforce_consumer_goods_cloud/schema_helper.rb
integrations/lib/multiwoven/integrations/rollout.rb
integrations/lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/schema_helper.rb

[](fix: Salesforce consumer goods cloud schema helper picklist type)
None

fix: Salesforce consumer goods cloud schema helper picklist type

---

ui/src/views/Activate/Syncs/EditSync/EditSync.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/ConfigureSyncs.tsx
ui/src/views/Activate/Syncs/SyncForm/ConfigureSyncs/SelectStreams.tsx
ui/src/views/Activate/Syncs/SyncForm/SyncForm.tsx
ui/src/views/Activate/Syncs/types.ts

Added support for cursor field implementation during configuring syncs.

feat: support for cursor field during syncs config

---

server/lib/reverse_etl/transformers/user_mapping.rb
server/spec/lib/reverse_etl/transformers/user_mapping_spec.rb

fix: Remove \n from rendered liquid template data
None
Wrote rspec unit tests

fix: Remove \n from rendered liquid template data

---

server/app/contracts/sync_contracts.rb
server/app/models/sync.rb
server/spec/contracts/sync_contracts_spec.rb
server/spec/models/sync_spec.rb

fix: Add greater than zero validation for sync_interval
None
Wrote rspec unit test

fix: Add greater than zero validation for sync_interval

---

ui/src/views/Activate/Syncs/SyncRuns/SyncRunTableItem.tsx
ui/src/views/Activate/Syncs/__tests__/SyncRunsTableItem.test.tsx
ui/src/views/Activate/Syncs/constants.ts
ui/src/views/Activate/Syncs/types.ts

Added rows skipped in the sync runs table

feat: added skip rows in the sync runs table

---

server/Gemfile
server/Gemfile.lock
server/db/data/20240513072634_add_roles.rb
server/db/data/20240513073101_add_resources.rb
server/db/data_schema.rb
server/db/migrate/20240506111708_create_resources.rb
server/db/migrate/20240506111803_create_roles.rb
server/db/schema.rb

feat: Add role and resource migration

---

server/Gemfile
server/Gemfile.lock

chore: Update integration gem version to 0.1.67 (Athena source, Zendesk & HTTP destination)
None
None

chore: Update integration gem version to 0.1.67 (Athena source, Zendesk & HTTP destination)

---

integrations/Gemfile.lock
integrations/lib/multiwoven/integrations/rollout.rb
integrations/lib/multiwoven/integrations/source/clickhouse/icon.svg

Quick fix for clickhouse connector icon as it was not rendering
Localhost

fix: clickhouse connector icon render

---

server/app/contracts/sync_contracts.rb
server/spec/contracts/sync_contracts_spec.rb

fix(CE): Fix sync name validation error due to contract failure
None

fix(CE): Fix sync name validation error due to contract failure

---

git-hooks/commit-msg

fix(CE): Update commit message regex to follow git convention
None
Tested locally

fix(CE): Update commit message regex to follow git convention

---

.github/workflows/deploy-server.yml
.github/workflows/deploy-ui.yml
.github/workflows/release.yaml
.github/workflows/sync-ce-commits.yaml

On workflow failure, report error to AppSignal.
[INFRA-941)(https://linear.app/ai-squared/issue/INFRA-941/appsignal-notification-on-github-workflows-failure)

feat(CE): on_failure report error to AppSignal

---

.github/workflows/server-docker-hub-push-tags-amd.yaml
.github/workflows/ui-docker-hub-push-tags-amd.yml

Update workflow to push images to dockerhub when new release is created. This is corresponding to the EE PR:
https://github.com/Multiwoven/multiwoven-ee/pull/953
Cherrypick workflow from EE will not work, as PAT doesnt have access to  push changes to workflow from another workflow.

feat(CE): update workflow to push images to dockerhub when new release is created

---

ui/src/components/SteppedForm/SteppedForm.tsx
ui/src/services/connectors.ts
ui/src/views/Connectors/Destinations/DestinationsForm/SelectDestinations/SelectDestinations.tsx
ui/src/views/Connectors/Sources/SourcesForm/SelectDataSourcesForm/SelectDataSourcesForm.tsx

Fixed the error where connector definitions API was not rendering in the page

fix(CE): connector listing error
